on: [push]

jobs:
  fawltydeps:
    runs-on: ubuntu-latest
    name: "fawltydeps"
    steps:
      - uses: davidslusser/actions_python_fawltydeps@main
        with:
          pip_install_command: "pip install fawltydeps"
          python_version: "3.13"
