name: Create and publish a Docker image

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: davidslusser/actions_docker_ghcr@initial
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
