on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: davidslusser/hello-world-composite-action@main
        with:
          who-to-greet: 'Mona the Octocat'
          src: "src"
          coveralls_repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
