on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    name: "mypy"
    steps:
      - uses: davidslusser/actions_python_mypy@main
        with:
          src: "src"
          options: ""
          python_version: "3.9"
