on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    name: "mypy"
    steps:
      - uses: davidslusser/actions_python_mypy@main
        with:
          src: "src"
          options: "-v"
          pip_install_command: "pip install -e .[dev]"
          python_version: "3.9"
