on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: "pylint"
    steps:
      - uses: davidslusser/actions_python_pylint@test
        with:
            src: "src"
            pip_install_command: "pip install -e .[dev]"
